// Components
import { BryanChecker } from '@/components/global';

// Types
import type { Metadata } from 'next';

// Utilities
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <BryanChecker />
        {children}
      </body>
    </html>
  );
};
