import type { IconType } from "react-icons";
import {
  FaAnchor,
  FaBell,
  FaBridge,
  FaCar,
  FaCheese,
  FaCity,
  FaCow,
  FaDice,
  FaFish,
  FaFlagCheckered,
  FaHorse,
  FaIndustry,
  FaLandmark,
  FaLandmarkDome,
  FaLeaf,
  FaMonument,
  FaMountain,
  FaMountainSun,
  FaMusic,
  FaOilWell,
  FaRoute,
  FaSailboat,
  FaSeedling,
  FaShip,
  FaSnowflake,
  FaStar,
  FaSun,
  FaTractor,
  FaTree,
  FaTreeCity,
  FaUmbrellaBeach,
  FaWater,
  FaWheatAwn,
} from "react-icons/fa6";

export type RegionItem = {
  name: string;
  icon: IconType;
};

export const US_STATES: RegionItem[] = [
  { name: "Alabama", icon: FaSeedling },
  { name: "Alaska", icon: FaSnowflake },
  { name: "Arizona", icon: FaSun },
  { name: "Arkansas", icon: FaTree },
  { name: "California", icon: FaWater },
  { name: "Colorado", icon: FaMountain },
  { name: "Connecticut", icon: FaBridge },
  { name: "Delaware", icon: FaAnchor },
  { name: "Florida", icon: FaUmbrellaBeach },
  { name: "Georgia", icon: FaLeaf },
  { name: "Hawaii", icon: FaWater },
  { name: "Idaho", icon: FaMountainSun },
  { name: "Illinois", icon: FaCity },
  { name: "Indiana", icon: FaFlagCheckered },
  { name: "Iowa", icon: FaTractor },
  { name: "Kansas", icon: FaWheatAwn },
  { name: "Kentucky", icon: FaHorse },
  { name: "Louisiana", icon: FaShip },
  { name: "Maine", icon: FaFish },
  { name: "Maryland", icon: FaAnchor },
  { name: "Massachusetts", icon: FaLandmark },
  { name: "Michigan", icon: FaCar },
  { name: "Minnesota", icon: FaWater },
  { name: "Mississippi", icon: FaWater },
  { name: "Missouri", icon: FaMonument },
  { name: "Montana", icon: FaMountain },
  { name: "Nebraska", icon: FaWheatAwn },
  { name: "Nevada", icon: FaDice },
  { name: "New Hampshire", icon: FaTree },
  { name: "New Jersey", icon: FaRoute },
  { name: "New Mexico", icon: FaSun },
  { name: "New York", icon: FaCity },
  { name: "North Carolina", icon: FaSailboat },
  { name: "North Dakota", icon: FaSnowflake },
  { name: "Ohio", icon: FaIndustry },
  { name: "Oklahoma", icon: FaOilWell },
  { name: "Oregon", icon: FaTree },
  { name: "Pennsylvania", icon: FaBell },
  { name: "Rhode Island", icon: FaAnchor },
  { name: "South Carolina", icon: FaUmbrellaBeach },
  { name: "South Dakota", icon: FaMonument },
  { name: "Tennessee", icon: FaMusic },
  { name: "Texas", icon: FaStar },
  { name: "Utah", icon: FaMountainSun },
  { name: "Vermont", icon: FaLeaf },
  { name: "Virginia", icon: FaLandmarkDome },
  { name: "Washington", icon: FaTreeCity },
  { name: "West Virginia", icon: FaMountain },
  { name: "Wisconsin", icon: FaCheese },
  { name: "Wyoming", icon: FaCow },
];

export const CANADA_PROVINCES: RegionItem[] = [
  { name: "Alberta", icon: FaMountain },
  { name: "British Columbia", icon: FaTree },
  { name: "Manitoba", icon: FaSnowflake },
  { name: "New Brunswick", icon: FaAnchor },
  { name: "Newfoundland and Labrador", icon: FaFish },
  { name: "Nova Scotia", icon: FaSailboat },
  { name: "Ontario", icon: FaCity },
  { name: "Prince Edward Island", icon: FaLeaf },
  { name: "Quebec", icon: FaLandmarkDome },
  { name: "Saskatchewan", icon: FaWheatAwn },
];
